---
  - name: Create transport zones
    vmware.ansible_for_nsxt.nsxt_transport_zones:
      hostname:                     "{{ nsxapp.ip }}"
      username:                     "{{ nsxapp.user }}"
      password:                     "{{ nsxapp.password }}"
      validate_certs:               False
      resource_type:                "TransportZone"
      display_name:                 "{{ item.value.display_name }}"
      transport_type:               "{{ item.value.transport_type }}"
      state:                        "{{ item.value.state }}"
    with_dict:
      - "{{ transport_zones }}"

  - name: Create a unique IP pool for all TEPs  
    vmware.ansible_for_nsxt.nsxt_ip_pools:
      hostname:                     "{{ nsxapp.ip }}"
      username:                     "{{ nsxapp.user }}"
      password:                     "{{ nsxapp.password }}"
      validate_certs: False
      display_name:                 "{{ TEP_Pool.display_name }}"
      subnets:                      "{{ TEP_Pool.subnets }}"
      state:                        "{{ TEP_Pool.state }}"
    
  # create mamangement and vmotion VLAN segments in the default vlan TZ
  - name: Create management segment
    vmware.ansible_for_nsxt.nsxt_policy_segment:
      hostname:                     "{{ nsxapp.ip }}"
      username:                     "{{ nsxapp.user }}"
      password:                     "{{ nsxapp.password }}"
      validate_certs:               False
      display_name:                 "{{ mgmt_pg }}-seg"
      vlan_ids:                     "{{ mgmt_vlan }}"
      admin_state:                  "UP"
      transport_zone_display_name:  "nsx-vlan-transportzone"
      state:                        "present"

  - name: Create vMotion segment
    vmware.ansible_for_nsxt.nsxt_policy_segment:
      hostname:                     "{{ nsxapp.ip }}"
      username:                     "{{ nsxapp.user }}"
      password:                     "{{ nsxapp.password }}"
      validate_certs:               False
      display_name:                 "vMotion-seg"
      vlan_ids:                     "{{ vmotion_vlan }}"
      admin_state:                  "UP"
      transport_zone_display_name:  "nsx-vlan-transportzone"
      state:                        "present"

  - name: Create an overlay segment
    vmware.ansible_for_nsxt.nsxt_policy_segment:
      hostname:                     "{{ nsxapp.ip }}"
      username:                     "{{ nsxapp.user }}"
      password:                     "{{ nsxapp.password }}"
      validate_certs:               False
      display_name:                 "overlay-segment"
      admin_state:                  "UP"
      transport_zone_display_name:  "nsx-overlay-transportzone"
      state:                        "present"




  - name: Create an Uplink Profile with 2 uplinks
    vmware.ansible_for_nsxt.nsxt_uplink_profiles:
      hostname:                     "{{ nsxapp.ip }}"
      username:                     "{{ nsxapp.user }}"
      password:                     "{{ nsxapp.password }}"
      validate_certs: False
      display_name:                 "uplinkProfile1"
      mtu:                          1600
      resource_type:                "UplinkHostSwitchProfile"
      teaming:
        active_list: 
        - uplink_name:              "uplink-1"
          uplink_type:              PNIC
        - uplink_name:              "uplink-2"
          uplink_type:              PNIC
        policy:                     FAILOVER_ORDER
      transport_vlan:               0
      state:                        "present"

